name: paper

services:
    app:
        build:
            context: ..
            dockerfile: .docker/Dockerfile
            target: base
        volumes:
            - ../:/var/www/html:cached
        ports:
            - "8016:8080"
            - "5176:5176"
