services:
    paper:
        build:
            context: ..
            dockerfile: .docker/Dockerfile
            target: base
        tty: true
        volumes:
            - ../:/app:cached
        ports:
            - 8016:8000
            - 5176:5176
